package final_java;

//Congratulation Form class
public class CongratzForm extends javax.swing.JFrame {

    public CongratzForm() {
        initComponents();
        setSize(428, 318);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BELIEVE IN YOURSELF, NEVER LOSE YOUR FAITH");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 120, 340, 50);

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HWAITING !");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 170, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/elizabethchan/Documents/java/final_java/pinkback.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-160, -160, 590, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
