package final_java;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class LoginForm extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    
    public LoginForm() {
        initComponents();
        setSize(400, 315);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        JLabelDrag = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonCancel = new javax.swing.JButton();
        jButtonLOGIN = new javax.swing.JButton();
        jLabelRegister = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login Form");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(239, 245, 247));
        jPanel1.setLayout(null);

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 148, 120));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose);
        jLabelClose.setBounds(366, 0, 16, 44);

        jLabel3.setFont(new java.awt.Font("Apple Chancery", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 148, 120));
        jLabel3.setText("Login");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(32, 0, 70, 44);

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 148, 120));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMin);
        jLabelMin.setBounds(344, 0, 10, 44);

        JLabelDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JLabelDragMouseDragged(evt);
            }
        });
        JLabelDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JLabelDragMousePressed(evt);
            }
        });
        jPanel1.add(JLabelDrag);
        JLabelDrag.setBounds(0, 0, 400, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 50);

        jPanel2.setBackground(new java.awt.Color(227, 238, 255));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 153));
        jLabel5.setText("Password :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 121, 86, 22);

        jLabel6.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 153));
        jLabel6.setText("Username :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 65, 86, 22);

        jTextField1.setBackground(new java.awt.Color(255, 247, 255));
        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel2.add(jTextField1);
        jTextField1.setBounds(152, 62, 160, 27);

        jPasswordField1.setBackground(new java.awt.Color(255, 247, 255));
        jPasswordField1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPasswordField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(152, 118, 160, 27);

        jButtonCancel.setBackground(new java.awt.Color(255, 82, 102));
        jButtonCancel.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(255, 82, 102));
        jButtonCancel.setText("CANCEL");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancel);
        jButtonCancel.setBounds(100, 160, 90, 38);

        jButtonLOGIN.setBackground(new java.awt.Color(255, 82, 102));
        jButtonLOGIN.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jButtonLOGIN.setForeground(new java.awt.Color(255, 82, 102));
        jButtonLOGIN.setText("LOGIN");
        jButtonLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLOGINActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLOGIN);
        jButtonLOGIN.setBounds(220, 160, 87, 38);

        jLabelRegister.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabelRegister.setForeground(new java.awt.Color(102, 66, 153));
        jLabelRegister.setText("Click here to create a new account");
        jLabelRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelRegister);
        jLabelRegister.setBounds(100, 210, 210, 16);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 50, 400, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterMouseClicked
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame f = new RegisterForm();
                f.setVisible(true);
                f.setLocationRelativeTo(null);
            }
        });

        this.dispose(); //close the Login form
    }//GEN-LAST:event_jLabelRegisterMouseClicked

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLOGINActionPerformed
        PreparedStatement ps;
        ResultSet rs;
        String usrname = jTextField1.getText();
        String pass = String.valueOf(jPasswordField1.getPassword());
        
        String query = "SELECT * FROM people WHERE people_user = ? AND people_pass = ? ";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            
            ps.setString(1, usrname);
            ps.setString(2, pass);
            
            rs = ps.executeQuery();
            
            if (rs.next())
            {
                HomeForm hf = new HomeForm();
                hf.setVisible(true);
                hf.pack();
                java.awt.EventQueue.invokeLater(() -> hf.setLocationRelativeTo(null));
                hf.setSize(656,398);
                hf.jLabel3.setText("Welcome, ");
                hf.jLabel1.setText(usrname);
                
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Incorrect Username or Password", "Login Failed", JOptionPane.PLAIN_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonLOGINActionPerformed

    private void JLabelDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_JLabelDragMouseDragged

    private void JLabelDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_JLabelDragMousePressed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelDrag;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonLOGIN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
