package final_java;

//the first form to be shown when the program run
public class MainForm extends javax.swing.JFrame {

    public MainForm() {
        initComponents();
        setSize(938, 599);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("LiSong Pro", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(83, 51, 237));
        jLabel1.setText("AMOUR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 160, 220, 80);

        jButtonLogin.setFont(new java.awt.Font("Malayalam MN", 2, 18)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 148, 120));
        jButtonLogin.setText("LOGIN");
        jButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonLogin);
        jButtonLogin.setBounds(430, 260, 110, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/elizabethchan/Documents/java/final_java/soulmateback.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-120, 0, 1150, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                javax.swing.JFrame f = new LoginForm();
                f.setVisible(true);
                f.setLocationRelativeTo(null);
            }
        });
        this.dispose();
    }//GEN-LAST:event_jButtonLoginMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
