package final_java;

public class ResultForm extends javax.swing.JFrame {

    public ResultForm() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LabelName = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton_Great_ = new javax.swing.JButton();
        jButton_No_ = new javax.swing.JButton();
        LabelAge = new javax.swing.JLabel();
        LabelHeight = new javax.swing.JLabel();
        lbl_img = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Labeltrait1 = new javax.swing.JLabel();
        Labeltrait2 = new javax.swing.JLabel();
        Labeltrait3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        condet1 = new javax.swing.JLabel();
        condet2 = new javax.swing.JLabel();
        condet3 = new javax.swing.JLabel();
        condet4 = new javax.swing.JLabel();
        condet5 = new javax.swing.JLabel();
        condet6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(227, 238, 255));
        jPanel2.setLayout(null);

        LabelName.setBackground(new java.awt.Color(255, 255, 255));
        LabelName.setFont(new java.awt.Font("Luminari", 0, 18)); // NOI18N
        LabelName.setForeground(new java.awt.Color(102, 51, 153));
        LabelName.setText("Name ");
        jPanel2.add(LabelName);
        LabelName.setBounds(150, 260, 110, 30);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 51, 153));
        jLabel12.setText("Personal traits : ");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(80, 380, 130, 22);

        jButton_Great_.setBackground(new java.awt.Color(255, 82, 102));
        jButton_Great_.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jButton_Great_.setForeground(new java.awt.Color(255, 82, 102));
        jButton_Great_.setText("GREAT !");
        jButton_Great_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Great_ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Great_);
        jButton_Great_.setBounds(220, 630, 90, 38);

        jButton_No_.setBackground(new java.awt.Color(255, 82, 102));
        jButton_No_.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jButton_No_.setForeground(new java.awt.Color(255, 82, 102));
        jButton_No_.setText("NOT INTERESTED");
        jButton_No_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_No_ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_No_);
        jButton_No_.setBounds(50, 630, 140, 38);

        LabelAge.setBackground(new java.awt.Color(255, 255, 255));
        LabelAge.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        LabelAge.setForeground(new java.awt.Color(102, 51, 153));
        LabelAge.setText("Age ");
        jPanel2.add(LabelAge);
        LabelAge.setBounds(140, 300, 110, 30);

        LabelHeight.setBackground(new java.awt.Color(255, 255, 255));
        LabelHeight.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        LabelHeight.setForeground(new java.awt.Color(102, 51, 153));
        LabelHeight.setText("Height");
        jPanel2.add(LabelHeight);
        LabelHeight.setBounds(150, 340, 70, 30);

        lbl_img.setBackground(new java.awt.Color(255, 247, 255));
        lbl_img.setOpaque(true);
        jPanel2.add(lbl_img);
        lbl_img.setBounds(90, 60, 200, 190);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Apple Chancery", 0, 28)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 51, 153));
        jLabel11.setText("Found A Match !");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(90, 20, 210, 40);

        Labeltrait1.setBackground(new java.awt.Color(255, 255, 255));
        Labeltrait1.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        Labeltrait1.setForeground(new java.awt.Color(102, 51, 153));
        Labeltrait1.setText("trait1");
        jPanel2.add(Labeltrait1);
        Labeltrait1.setBounds(90, 410, 100, 22);

        Labeltrait2.setBackground(new java.awt.Color(255, 255, 255));
        Labeltrait2.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        Labeltrait2.setForeground(new java.awt.Color(102, 51, 153));
        Labeltrait2.setText("trait2");
        jPanel2.add(Labeltrait2);
        Labeltrait2.setBounds(150, 440, 110, 22);

        Labeltrait3.setBackground(new java.awt.Color(255, 255, 255));
        Labeltrait3.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        Labeltrait3.setForeground(new java.awt.Color(102, 51, 153));
        Labeltrait3.setText("trait3");
        jPanel2.add(Labeltrait3);
        Labeltrait3.setBounds(200, 410, 100, 22);

        jLabel13.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 51, 153));
        jLabel13.setText("Contact Detail  :");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(70, 480, 130, 22);

        condet1.setBackground(new java.awt.Color(255, 255, 255));
        condet1.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        condet1.setForeground(new java.awt.Color(102, 51, 153));
        condet1.setText("condet1");
        jPanel2.add(condet1);
        condet1.setBounds(60, 510, 150, 22);

        condet2.setBackground(new java.awt.Color(255, 255, 255));
        condet2.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        condet2.setForeground(new java.awt.Color(102, 51, 153));
        condet2.setText("condet2");
        jPanel2.add(condet2);
        condet2.setBounds(60, 550, 150, 22);

        condet3.setBackground(new java.awt.Color(255, 255, 255));
        condet3.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        condet3.setForeground(new java.awt.Color(102, 51, 153));
        condet3.setText("condet3");
        jPanel2.add(condet3);
        condet3.setBounds(60, 590, 150, 20);

        condet4.setBackground(new java.awt.Color(255, 255, 255));
        condet4.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        condet4.setForeground(new java.awt.Color(102, 51, 153));
        condet4.setText("condet4");
        jPanel2.add(condet4);
        condet4.setBounds(210, 490, 150, 22);

        condet5.setBackground(new java.awt.Color(255, 255, 255));
        condet5.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        condet5.setForeground(new java.awt.Color(102, 51, 153));
        condet5.setText("condet5");
        jPanel2.add(condet5);
        condet5.setBounds(170, 530, 160, 22);

        condet6.setBackground(new java.awt.Color(255, 255, 255));
        condet6.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        condet6.setForeground(new java.awt.Color(102, 51, 153));
        condet6.setText("condet6");
        jPanel2.add(condet6);
        condet6.setBounds(170, 570, 150, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Great_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Great_ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame f = new CongratzForm();
                f.setVisible(true);
                f.setLocationRelativeTo(null);
                for (javax.swing.JFrame frame : SearchForm.matchWindows)
                {
                    frame.dispose();
                }
                
            }
        });
        this.dispose();
    }//GEN-LAST:event_jButton_Great_ActionPerformed

    private void jButton_No_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_No_ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame f = new LoginForm();
                f.setVisible(true);
                f.setLocationRelativeTo(null);
            }
        });
        this.dispose(); //close the Result form
    }//GEN-LAST:event_jButton_No_ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel LabelAge;
    public javax.swing.JLabel LabelHeight;
    public javax.swing.JLabel LabelName;
    public javax.swing.JLabel Labeltrait1;
    public javax.swing.JLabel Labeltrait2;
    public javax.swing.JLabel Labeltrait3;
    public javax.swing.JLabel condet1;
    public javax.swing.JLabel condet2;
    public javax.swing.JLabel condet3;
    public javax.swing.JLabel condet4;
    public javax.swing.JLabel condet5;
    public javax.swing.JLabel condet6;
    private javax.swing.JButton jButton_Great_;
    private javax.swing.JButton jButton_No_;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lbl_img;
    // End of variables declaration//GEN-END:variables
}
