package final_java;

public class SorryForm extends javax.swing.JFrame {

    public SorryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelSearch = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("SORRY NO MATCH :(");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 90, 160, 50);

        jLabelSearch.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabelSearch.setForeground(new java.awt.Color(0, 0, 255));
        jLabelSearch.setText("SEARCH AGAIN ");
        jLabelSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(51, 153, 255), new java.awt.Color(51, 153, 255), null));
        jLabelSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSearchMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelSearch);
        jLabelSearch.setBounds(200, 170, 100, 40);

        jLabelClose.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(0, 0, 255));
        jLabelClose.setText("CLOSE");
        jLabelClose.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(51, 153, 255), new java.awt.Color(51, 153, 255), null));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelClose);
        jLabelClose.setBounds(110, 170, 50, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/elizabethchan/Documents/java/final_java/blueback.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame f = new SearchForm();
                f.setVisible(true);
                f.setLocationRelativeTo(null);
            }
        });
        
        this.dispose();
    }//GEN-LAST:event_jLabelSearchMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelSearch;
    // End of variables declaration//GEN-END:variables
}
