package final_java;

import java.awt.Image;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.NumberFormatter;

public class UpdateForm extends javax.swing.JFrame {

    public UpdateForm() {
        initComponents();
    }

    int xMouse;
    int yMouse;
    String imagePath = null;    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabelDrag = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_nm = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCombo_trait1 = new javax.swing.JComboBox<>();
        jCombo_trait2 = new javax.swing.JComboBox<>();
        jCombo_trait3 = new javax.swing.JComboBox<>();
        jCombo_cont1 = new javax.swing.JComboBox<>();
        jText_cont1 = new javax.swing.JTextField();
        jCombo_cont2 = new javax.swing.JComboBox<>();
        jText_cont2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPasswordField_pass = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jPasswordField_repass = new javax.swing.JPasswordField();
        jButton_cancel = new javax.swing.JButton();
        jButton_Update_ = new javax.swing.JButton();
        NumberFormat longFormat = NumberFormat.getIntegerInstance();

        NumberFormatter numberFormatter = new NumberFormatter(longFormat);
        numberFormatter.setValueClass(Long.class); //optional, ensures you will always get a long value
        numberFormatter.setAllowsInvalid(false); //this is the key!!
        numberFormatter.setMinimum(0l); //Optional
        jFormattedTextField_ht = new javax.swing.JFormattedTextField(numberFormatter);
        NumberFormat longFormat2 = NumberFormat.getIntegerInstance();

        NumberFormatter numberFormatter2 = new NumberFormatter(longFormat);
        numberFormatter2.setValueClass(Long.class); //optional, ensures you will always get a long value
        numberFormatter2.setAllowsInvalid(false); //this is the key!!
        numberFormatter2.setMinimum(0l); //Optional
        jFormattedTextField_age = new javax.swing.JFormattedTextField(numberFormatter2);
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbl_img = new javax.swing.JLabel();
        Btn_chooseImg = new javax.swing.JButton();
        jLabelUsr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(239, 245, 247));
        jPanel1.setLayout(null);

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 148, 120));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose);
        jLabelClose.setBounds(366, 0, 16, 44);

        jLabel3.setFont(new java.awt.Font("Apple Chancery", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 148, 120));
        jLabel3.setText("Update");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(32, 0, 74, 44);

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 148, 120));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMin);
        jLabelMin.setBounds(344, 0, 10, 44);

        jLabelDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelDragMouseDragged(evt);
            }
        });
        jLabelDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelDragMousePressed(evt);
            }
        });
        jPanel1.add(jLabelDrag);
        jLabelDrag.setBounds(0, 0, 400, 50);

        jPanel2.setBackground(new java.awt.Color(227, 238, 255));
        jPanel2.setLayout(null);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 153));
        jLabel6.setText("Height :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(70, 140, 86, 22);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 153));
        jLabel7.setText("Image :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(60, 370, 86, 20);

        jTextField_nm.setBackground(new java.awt.Color(255, 247, 255));
        jTextField_nm.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel2.add(jTextField_nm);
        jTextField_nm.setBounds(160, 60, 160, 27);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 51, 153));
        jLabel8.setText("Age :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(70, 100, 86, 22);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("female");
        jRadioButton1.setContentAreaFilled(false);
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(160, 180, 80, 23);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 51, 153));
        jLabel10.setText("Gender :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(70, 180, 86, 22);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("male");
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(250, 180, 70, 23);

        jLabel11.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 51, 153));
        jLabel11.setText("Contact Detail  :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(70, 270, 130, 22);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 51, 153));
        jLabel12.setText("Personal traits :");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(70, 210, 130, 22);

        jCombo_trait1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adventurous", "Appreciative", "Caring", "Charismatic", "Confident", "Creative", "Dedicated", "Earnest", "Exciting", "Extraordinary", "Faithful", "Flexible", "Funny", "Generous", "Honorable", "Humorous", "Kind", "Loyal", "Modest", "Observant", "Optimistic", "Organized", "Patient", "Protective", "Realistic", "Relaxed", "Sociable", "Sympathetic", "Trusting", "Warm" }));
        jPanel2.add(jCombo_trait1);
        jCombo_trait1.setBounds(60, 240, 96, 27);

        jCombo_trait2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adventurous", "Appreciative", "Caring", "Charismatic", "Confident", "Creative", "Dedicated", "Earnest", "Exciting", "Extraordinary", "Faithful", "Flexible", "Funny", "Generous", "Honorable", "Humorous", "Kind", "Loyal", "Modest", "Obeservant", "Optimistic", "Organized", "Patient", "Protective", "Realistic", "Relaxed", "Sociable", "Sympathetic", "Trusting", "Warm" }));
        jPanel2.add(jCombo_trait2);
        jCombo_trait2.setBounds(160, 240, 96, 27);

        jCombo_trait3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adventurous", "Appreciative", "Caring", "Charismatic", "Confident", "Creative", "Dedicated", "Earnest", "Exciting", "Extraordinary", "Faithful", "Flexible", "Funny", "Generous", "Honorable", "Humorous", "Kind", "Loyal", "Modest", "Obeservant", "Optimistic", "Organized", "Patient", "Protective", "Realistic", "Relaxed", "Sociable", "Sympathetic", "Trusting", "Warm" }));
        jPanel2.add(jCombo_trait3);
        jCombo_trait3.setBounds(260, 240, 96, 27);

        jCombo_cont1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WhatsApp", "Line", "Instagram", "Twitter", "Facebook", "Snapchat" }));
        jPanel2.add(jCombo_cont1);
        jCombo_cont1.setBounds(60, 300, 96, 27);

        jText_cont1.setBackground(new java.awt.Color(255, 247, 255));
        jText_cont1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel2.add(jText_cont1);
        jText_cont1.setBounds(160, 300, 160, 27);

        jCombo_cont2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WhatsApp", "Line", "Instagram", "Twitter", "Facebook", "Snapchat" }));
        jPanel2.add(jCombo_cont2);
        jCombo_cont2.setBounds(60, 330, 96, 27);

        jText_cont2.setBackground(new java.awt.Color(255, 247, 255));
        jText_cont2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel2.add(jText_cont2);
        jText_cont2.setBounds(160, 330, 160, 27);

        jLabel9.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 51, 153));
        jLabel9.setText("Username :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(60, 20, 86, 22);

        jLabel13.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 51, 153));
        jLabel13.setText("Password :");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(60, 510, 86, 22);

        jPasswordField_pass.setBackground(new java.awt.Color(255, 247, 255));
        jPasswordField_pass.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPasswordField_pass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(jPasswordField_pass);
        jPasswordField_pass.setBounds(170, 510, 160, 27);

        jLabel14.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 51, 153));
        jLabel14.setText("Retype Pass :");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(60, 550, 100, 22);

        jPasswordField_repass.setBackground(new java.awt.Color(255, 247, 255));
        jPasswordField_repass.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPasswordField_repass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(jPasswordField_repass);
        jPasswordField_repass.setBounds(170, 550, 160, 27);

        jButton_cancel.setBackground(new java.awt.Color(255, 82, 102));
        jButton_cancel.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jButton_cancel.setForeground(new java.awt.Color(255, 82, 102));
        jButton_cancel.setText("CANCEL");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_cancel);
        jButton_cancel.setBounds(80, 610, 90, 38);

        jButton_Update_.setBackground(new java.awt.Color(255, 82, 102));
        jButton_Update_.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jButton_Update_.setForeground(new java.awt.Color(255, 82, 102));
        jButton_Update_.setText("UPDATE");
        jButton_Update_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Update_ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Update_);
        jButton_Update_.setBounds(200, 610, 106, 38);

        jFormattedTextField_ht.setBackground(new java.awt.Color(255, 247, 255));
        jFormattedTextField_ht.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel2.add(jFormattedTextField_ht);
        jFormattedTextField_ht.setBounds(160, 140, 160, 26);

        jFormattedTextField_age.setBackground(new java.awt.Color(255, 247, 255));
        jFormattedTextField_age.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel2.add(jFormattedTextField_age);
        jFormattedTextField_age.setBounds(160, 100, 160, 26);

        jLabel1.setText("cm");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(320, 140, 45, 20);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Luminari", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 51, 153));
        jLabel15.setText("Name :");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(70, 60, 86, 22);

        lbl_img.setBackground(new java.awt.Color(255, 247, 255));
        lbl_img.setOpaque(true);
        jPanel2.add(lbl_img);
        lbl_img.setBounds(170, 360, 190, 130);

        Btn_chooseImg.setText("Choose Image");
        Btn_chooseImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_chooseImgActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_chooseImg);
        Btn_chooseImg.setBounds(50, 410, 120, 29);

        jLabelUsr.setFont(new java.awt.Font("Nanum Myeongjo", 1, 24)); // NOI18N
        jLabelUsr.setForeground(new java.awt.Color(102, 51, 153));
        jLabelUsr.setText("JLabelUsr");
        jPanel2.add(jLabelUsr);
        jLabelUsr.setBounds(160, 10, 120, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.setLocationRelativeTo(null);
        lf.pack();
        lf.setSize(400, 315);
        
        this.dispose();
    }//GEN-LAST:event_jButton_cancelActionPerformed

    //insert the updatted data to the database
    private void jButton_Update_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Update_ActionPerformed
        if(CheckInputs() && jLabelUsr.getText() != null){
            String name = jTextField_nm.getText();
            int age = new Long((long) jFormattedTextField_age.getValue()).intValue();
            double height = new Long((long) jFormattedTextField_ht.getValue()).intValue();
            String gender = null;
            if (jRadioButton1.isEnabled()){
                gender = "female";
            }
            else if (jRadioButton2.isEnabled()){
                gender = "male";
            }

            String trait1 = (String) jCombo_trait1.getSelectedItem();
            String trait2 = (String) jCombo_trait2.getSelectedItem();
            String trait3 = (String) jCombo_trait3.getSelectedItem();

            String contactchoose1 = (String) jCombo_cont1.getSelectedItem();
            String contact1 = jText_cont1.getText();
            String contactchoose2 = (String) jCombo_cont2.getSelectedItem();
            String contact2 = jText_cont2.getText();

            String usrname = jLabelUsr.getText();
            String pass = String.valueOf(jPasswordField_pass.getPassword());
            String repass = String.valueOf(jPasswordField_repass.getPassword());

            if (pass.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Add a password");
            }
            else if (!pass.equals(repass))
            {
                JOptionPane.showMessageDialog(null, "Retype the password again");
            }

            else
            {
                PreparedStatement pst;
                String query = "UPDATE people SET people_pass = ?, people_name = ?, people_age = ?, people_gender = ?"
                        + ", people_height = ?, WhatsApp = ?, Line = ?, Instagram = ?, Twitter = ?, Facebook = ?"
                        + ", Snapchat = ?, people_trait1 = ?, people_trait2 = ?, people_trait3 = ?, image = ? WHERE people_user = ?";

                try {
                    pst = MyConnection.getConnection().prepareStatement(query);

                    pst.setString(1, pass);
                    pst.setString(2, name);
                    pst.setInt(3, age);
                    pst.setString(4, gender);
                    pst.setDouble(5, height);
                    pst.setString(6, null);
                    pst.setString(7, null);
                    pst.setString(8, null);
                    pst.setString(9, null);
                    pst.setString(10, null);
                    pst.setString(11, null);
                    pst.setString(12, trait1);
                    pst.setString(13, trait2);
                    pst.setString(14, trait3);
                    pst.setString(15, imagePath);
                    pst.setString(16, usrname);

                    addCondet(pst, contactchoose1, contact1);
                    addCondet(pst, contactchoose2, contact2);

                    if (pst.executeUpdate() > 0)
                    {
                        this.dispose();
                        JOptionPane.showMessageDialog(null, "User Updated");
                        javax.swing.JFrame f = new LoginForm();
                        f.setVisible(true);
                        f.setLocationRelativeTo(null);
                    }

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "One or more fields are empty or wrong");
        }
    }//GEN-LAST:event_jButton_Update_ActionPerformed

    // Check input fields. If one or more fields are empty then cannot update
    public boolean CheckInputs(){
        if(jTextField_nm.getText() == null || jFormattedTextField_age.getText() == null || jFormattedTextField_ht.getText() == null){
            return false;
        }
        else{
            try{
                Long.parseLong(jFormattedTextField_ht.getText());
                return true;
            }catch(NumberFormatException ex){
                return false;
            }
        }
    }
    
    // Resize image
    public ImageIcon ResizeImg(String imagePath, byte[] pic){
        ImageIcon myImg = null;
        
        if(imagePath != null){
            myImg = new ImageIcon(imagePath);
        }else {
            myImg = new ImageIcon(pic);
        }
        
        Image img = myImg.getImage();
        Image img2 = img.getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }
    
    public void addCondet(PreparedStatement ps,String contact, String det){
        try{
            switch(contact){
                case "WhatsApp":
                    ps.setString(6, det);
                    break;
                case "Line":
                    ps.setString(7, det);
                    break;
                case "Instagram":
                    ps.setString(8, det);
                    break;
                case "Twitter":
                    ps.setString(9, det);
                    break;
                case "Facebook":
                    ps.setString(10, det);
                    break;
                case "Snapchat":
                    ps.setString(11, det);
                    break;
            }
        } catch (SQLException ex){
            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void Btn_chooseImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_chooseImgActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.image", "jpg", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lbl_img.setIcon(ResizeImg(path, null));
            imagePath = path;
        }
        else{
            System.out.println("No File Selected");
        }
    }//GEN-LAST:event_Btn_chooseImgActionPerformed

    private void jLabelDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDragMouseDragged
       int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
       
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabelDragMouseDragged

    private void jLabelDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabelDragMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_chooseImg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_Update_;
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JComboBox<String> jCombo_cont1;
    private javax.swing.JComboBox<String> jCombo_cont2;
    private javax.swing.JComboBox<String> jCombo_trait1;
    private javax.swing.JComboBox<String> jCombo_trait2;
    private javax.swing.JComboBox<String> jCombo_trait3;
    private javax.swing.JFormattedTextField jFormattedTextField_age;
    private javax.swing.JFormattedTextField jFormattedTextField_ht;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelDrag;
    private javax.swing.JLabel jLabelMin;
    public javax.swing.JLabel jLabelUsr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_pass;
    private javax.swing.JPasswordField jPasswordField_repass;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField_nm;
    private javax.swing.JTextField jText_cont1;
    private javax.swing.JTextField jText_cont2;
    private javax.swing.JLabel lbl_img;
    // End of variables declaration//GEN-END:variables
}
